"""FileFS - A simple file system implementation"""
from ._filefs import (
    create,
    destroy,
    mkfs,
    mount,
    umount,
    ismount,
    fopen,
    fread,
    fwrite,
    fclose,
    fseek,
    ftell,
    rewind,
    file_exist,
    dir_exist,
    remove,
    rename,
    move,
    copy,
    chdir,
    getcwd,
    mkdir,
    rmdir,
    opendir,
    readdir,
    closedir,
    begin,
    commit,
    rollback,
    # Constants
    DT_FILE,
    DT_DIR,
    DT_ROOT,
    SEEK_CUR,
    SEEK_END,
    SEEK_SET,
)

__all__ = [
    'create',
    'destroy',
    'mkfs',
    'mount',
    'umount',
    'ismount',
    'fopen',
    'fread',
    'fwrite',
    'fclose',
    'fseek',
    'ftell',
    'rewind',
    'file_exist',
    'dir_exist',
    'remove',
    'rename',
    'move',
    'copy',
    'chdir',
    'getcwd',
    'mkdir',
    'rmdir',
    'opendir',
    'readdir',
    'closedir',
    'begin',
    'commit',
    'rollback',
    'DT_FILE',
    'DT_DIR',
    'DT_ROOT',
    'SEEK_CUR',
    'SEEK_END',
    'SEEK_SET',
]

def __dir__():
    return sorted(__all__ + [
        "__all__", "__builtins__", "__cached__", "__doc__", "__file__",
        "__loader__", "__name__", "__package__", "__spec__",
    ])
